name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
   - lib/IMAGES/


  uses-material-design: true


  fonts:
     - family: dancingscript
       fonts:
         - asset: lib/font/DancingScript-VariableFont_wght.ttf

     - family: dancingscript
       fonts:
             - asset: lib/font2/DancingScript-VariableFont_wght.ttf
